spring:
  application:
    name: Echoes

  data:
    mongodb:
      uri: mongodb+srv://shubham2006621:Shubham%4022csu444@echoes.yedflog.mongodb.net/?retryWrites=true&w=majority&appName=echoes
      database: echoesdb
      # username: shubh
      # password: Shubham@22csu444
      auto-index-creation: true

  main:
    allow-circular-references: true


