spring.application.name=Echoes
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=echoesdb
#spring.data.mongodb.username=shubh
#spring.data.mongodb.password=Shubham@22csu444
spring.data.mongodb.auto-index-creation=true

