spring.application.name=Echoes
spring.data.mongodb.uri=mongodb+srv://shubham2006621:Shubham%4022csu444@echoes.yedflog.mongodb.net/?retryWrites=true&w=majority&appName=echoes
spring.data.mongodb.database=echoesdb
#spring.data.mongodb.username=shubh
#spring.data.mongodb.password=Shubham@22csu444
spring.data.mongodb.auto-index-creation=true

spring.main.allow-circular-references = true
