spring:
  profiles:
    active: dev

  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: "shubham22csu444@ncuindia.edu"
    password: "ysca wkyf rxye csah"  # wrap in quotes
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  kafka:
    bootstrap-servers: pkc-619z3.us-east1.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.shubham.Echoes.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='KY4JGZKOL7OQXQFN' password='cfltlbkMXbg9eJ1hIHEVdEr212EDx931WaHF53zcmfh8iQIxdAMQ45dFPEfe9xRg';
      session:
        timeout:
          ms: 45000


logging:
  level:
    net:
      shubham:
        Echoes: ERROR
